apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    run: my-nginx
    arktos.futurewei.com/network: test2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
