apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
    arktos.futurewei.com/network: test1
  name: kubernetes-test1
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
